import { NodeDef, EdgeDef } from "./types";

/**
 * 19 nodes positioned on a 2014 Subaru STI schematic.
 * Coordinates are percentages (0-100) of the viewport.
 * Layout: car viewed from above, front at top.
 */
export const NODES: NodeDef[] = [
  // Brake sensors — four corners, inboard of wheels
  {
    id: "brake-fl",
    label: "Brake FL",
    type: "sensor",
    x: 30,
    y: 20,
    unit: "°F",
    min: 150,
    max: 800,
    warnThreshold: 450,
    hotThreshold: 600,
    description: "Front-left brake rotor temperature sensor",
  },
  {
    id: "brake-fr",
    label: "Brake FR",
    type: "sensor",
    x: 70,
    y: 20,
    unit: "°F",
    min: 150,
    max: 800,
    warnThreshold: 450,
    hotThreshold: 600,
    description: "Front-right brake rotor temperature — running 28-40°F hotter than FL across Mission Raceway session",
  },
  {
    id: "brake-rl",
    label: "Brake RL",
    type: "sensor",
    x: 30,
    y: 76,
    unit: "°F",
    min: 100,
    max: 600,
    warnThreshold: 350,
    hotThreshold: 500,
    description: "Rear-left brake rotor temperature sensor",
  },
  {
    id: "brake-rr",
    label: "Brake RR",
    type: "sensor",
    x: 70,
    y: 76,
    unit: "°F",
    min: 100,
    max: 600,
    warnThreshold: 350,
    hotThreshold: 500,
    description: "Rear-right brake rotor temperature sensor",
  },
  // Tire sensors — four corners, outboard of brakes
  {
    id: "tire-fl",
    label: "Tire FL",
    type: "sensor",
    x: 19,
    y: 20,
    unit: "°F",
    min: 80,
    max: 250,
    warnThreshold: 200,
    hotThreshold: 230,
    description: "Front-left tire surface temperature — grip & wear indicator",
  },
  {
    id: "tire-fr",
    label: "Tire FR",
    type: "sensor",
    x: 81,
    y: 20,
    unit: "°F",
    min: 80,
    max: 250,
    warnThreshold: 200,
    hotThreshold: 230,
    description: "Front-right tire surface temperature — elevated from brake heat soak",
  },
  {
    id: "tire-rl",
    label: "Tire RL",
    type: "sensor",
    x: 19,
    y: 76,
    unit: "°F",
    min: 80,
    max: 220,
    warnThreshold: 180,
    hotThreshold: 210,
    description: "Rear-left tire surface temperature — traction monitoring",
  },
  {
    id: "tire-rr",
    label: "Tire RR",
    type: "sensor",
    x: 81,
    y: 76,
    unit: "°F",
    min: 80,
    max: 220,
    warnThreshold: 180,
    hotThreshold: 210,
    description: "Rear-right tire surface temperature — traction monitoring",
  },
  // Engine sensors — clustered around center-front
  {
    id: "egt",
    label: "EGT",
    type: "sensor",
    x: 50,
    y: 28,
    unit: "°F",
    min: 800,
    max: 1800,
    warnThreshold: 1500,
    hotThreshold: 1650,
    description: "Exhaust gas temperature probe — turbo health indicator",
  },
  {
    id: "boost",
    label: "Boost",
    type: "sensor",
    x: 40,
    y: 38,
    unit: "PSI",
    min: -14,
    max: 28,
    warnThreshold: 22,
    hotThreshold: 26,
    description: "Manifold boost pressure — turbo output",
  },
  {
    id: "oil-temp",
    label: "Oil Temp",
    type: "sensor",
    x: 60,
    y: 38,
    unit: "°F",
    min: 160,
    max: 300,
    warnThreshold: 250,
    hotThreshold: 280,
    description: "Engine oil temperature — lubrication health",
  },
  {
    id: "oil-pressure",
    label: "Oil Pres",
    type: "sensor",
    x: 40,
    y: 45,
    unit: "PSI",
    min: 0,
    max: 100,
    warnThreshold: 15,
    hotThreshold: 10,
    description: "Engine oil pressure — lubrication system health, low = critical",
  },
  {
    id: "wideband",
    label: "Wideband O₂",
    type: "sensor",
    x: 60,
    y: 45,
    unit: "AFR",
    min: 10,
    max: 18,
    warnThreshold: 14.7,
    hotThreshold: 12,
    description: "Wideband oxygen sensor — air/fuel ratio monitoring",
  },
  // Front-mounted cameras — across the front bumper
  {
    id: "teledyne-ir",
    label: "Teledyne IR",
    type: "camera",
    x: 30,
    y: 8,
    unit: "FPS",
    min: 0,
    max: 60,
    warnThreshold: 20,
    hotThreshold: 10,
    description: "Teledyne FLIR thermal camera — infrared heat mapping of track surface and obstacles",
  },
  {
    id: "lidar",
    label: "LiDAR",
    type: "camera",
    x: 44,
    y: 5,
    unit: "FPS",
    min: 0,
    max: 30,
    warnThreshold: 10,
    hotThreshold: 5,
    description: "3D LiDAR depth sensor — point cloud mapping for distance and object detection",
  },
  {
    id: "rgb-cam",
    label: "RGB Cam",
    type: "camera",
    x: 56,
    y: 5,
    unit: "FPS",
    min: 0,
    max: 120,
    warnThreshold: 25,
    hotThreshold: 15,
    description: "High-speed RGB camera — visual telemetry, driver monitoring, track recording",
  },
  {
    id: "weather-cam",
    label: "Weather Cam",
    type: "camera",
    x: 70,
    y: 8,
    unit: "FPS",
    min: 0,
    max: 30,
    warnThreshold: 10,
    hotThreshold: 5,
    description: "Weather and ambient conditions camera — rain, fog, light detection for adaptive driving",
  },
  // Link ECU G4X — center of car
  {
    id: "ecu",
    label: "Link G4X",
    type: "ecu",
    x: 50,
    y: 58,
    unit: "",
    min: 0,
    max: 100,
    warnThreshold: 80,
    hotThreshold: 95,
    description: "Link ECU G4X — central engine management, CAN bus hub",
  },
  // Jetson Orin — trunk area
  {
    id: "jetson",
    label: "Jetson Orin",
    type: "edge-compute",
    x: 50,
    y: 88,
    unit: "",
    min: 0,
    max: 100,
    warnThreshold: 75,
    hotThreshold: 90,
    description:
      "NVIDIA Jetson Orin — edge inference, telemetry aggregation, cloud sync",
  },
];

/**
 * 18 edges: 13 sensors → ECU (CAN), 4 cameras → Jetson (USB/CSI), ECU → Jetson (USB)
 */
export const EDGES: EdgeDef[] = [
  {
    id: "brake-fl-ecu",
    source: "brake-fl",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "brake-fr-ecu",
    source: "brake-fr",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "brake-rl-ecu",
    source: "brake-rl",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "brake-rr-ecu",
    source: "brake-rr",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "tire-fl-ecu",
    source: "tire-fl",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "tire-fr-ecu",
    source: "tire-fr",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "tire-rl-ecu",
    source: "tire-rl",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "tire-rr-ecu",
    source: "tire-rr",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  { id: "egt-ecu", source: "egt", target: "ecu", type: "can", label: "CAN" },
  {
    id: "boost-ecu",
    source: "boost",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "oil-ecu",
    source: "oil-temp",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "oil-pressure-ecu",
    source: "oil-pressure",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "wideband-ecu",
    source: "wideband",
    target: "ecu",
    type: "can",
    label: "CAN",
  },
  {
    id: "ecu-jetson",
    source: "ecu",
    target: "jetson",
    type: "usb",
    label: "USB 3.0",
  },
  // Cameras → Jetson directly
  {
    id: "teledyne-jetson",
    source: "teledyne-ir",
    target: "jetson",
    type: "usb",
    label: "USB 3.0",
  },
  {
    id: "lidar-jetson",
    source: "lidar",
    target: "jetson",
    type: "usb",
    label: "USB 3.0",
  },
  {
    id: "rgb-jetson",
    source: "rgb-cam",
    target: "jetson",
    type: "csi",
    label: "CSI",
  },
  {
    id: "weather-jetson",
    source: "weather-cam",
    target: "jetson",
    type: "csi",
    label: "CSI",
  },
];

export function getNode(id: string): NodeDef | undefined {
  return NODES.find((n) => n.id === id);
}

export function getConnectedEdges(nodeId: string): EdgeDef[] {
  return EDGES.filter((e) => e.source === nodeId || e.target === nodeId);
}

export function getConnectedNodes(nodeId: string): string[] {
  const edges = getConnectedEdges(nodeId);
  const ids = new Set<string>();
  for (const e of edges) {
    if (e.source !== nodeId) ids.add(e.source);
    if (e.target !== nodeId) ids.add(e.target);
  }
  return Array.from(ids);
}
