"""KiSTI - Data Models

Dataclasses representing vehicle telemetry state.
Replace with real CAN/IR/GPS data sources for production.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class RadarBand(Enum):
    """Valentine One radar band types."""
    X = "X"
    K = "K"
    Ka = "Ka"
    LASER = "Laser"


class AlertDirection(Enum):
    """Direction of detected radar source."""
    FRONT = "front"
    SIDE = "side"
    REAR = "rear"


@dataclass
class RadarAlert:
    """Single radar alert from Valentine One Gen2."""
    alert_id: str = ""
    band: RadarBand = RadarBand.Ka
    frequency_mhz: float = 34700.0
    front_signal: int = 0     # 0-8
    rear_signal: int = 0      # 0-8
    direction: AlertDirection = AlertDirection.FRONT
    priority: int = 0         # Higher = more urgent
    timestamp: float = 0.0


@dataclass
class RadarState:
    """Valentine One Gen2 radar detector state."""
    connected: bool = False
    active_alerts: List[RadarAlert] = field(default_factory=list)
    alert_count: int = 0
    muted: bool = False
    last_update: float = 0.0

    @property
    def has_alerts(self) -> bool:
        return len(self.active_alerts) > 0

    @property
    def priority_alert(self) -> Optional[RadarAlert]:
        if not self.active_alerts:
            return None
        return max(self.active_alerts, key=lambda a: a.priority)

    @property
    def highest_threat(self) -> int:
        if not self.active_alerts:
            return 0
        return max(max(a.front_signal, a.rear_signal) for a in self.active_alerts)


@dataclass
class CornerData:
    """Single wheel corner: tire temp, brake temp, wear, trend history."""
    tire_temp_c: float = 85.0
    brake_temp_c: float = 250.0
    tire_wear_pct: float = 1.0   # 1.0 = new, 0.0 = fully worn
    trend: List[float] = field(default_factory=lambda: [85.0] * 30)


@dataclass
class GPSData:
    """GPS position and velocity."""
    lat: float = 36.5725
    lon: float = -121.9486
    speed_kph: float = 0.0
    heading: float = 0.0


@dataclass
class OilPressureData:
    """Engine oil pressure telemetry."""
    psi: float = 45.0
    temp_c: float = 95.0
    trend: List[float] = field(default_factory=lambda: [45.0] * 30)


@dataclass
class CameraStatus:
    """Status of a single camera feed."""
    name: str = ""
    connected: bool = False
    fps: float = 0.0
    resolution: str = "0x0"


@dataclass
class FrontSensorSuite:
    """Front-of-car sensor array."""
    teledyne_ir: CameraStatus = field(default_factory=lambda: CameraStatus(
        name="Teledyne IR", connected=True, fps=30.0, resolution="640x480"))
    lidar_cam: CameraStatus = field(default_factory=lambda: CameraStatus(
        name="LiDAR", connected=True, fps=10.0, resolution="1024x64"))
    rgb_cam: CameraStatus = field(default_factory=lambda: CameraStatus(
        name="RGB", connected=True, fps=60.0, resolution="1920x1080"))
    weather_cam: CameraStatus = field(default_factory=lambda: CameraStatus(
        name="Weather", connected=True, fps=15.0, resolution="1280x720"))

    def all_cameras(self) -> List[CameraStatus]:
        return [self.teledyne_ir, self.lidar_cam, self.rgb_cam, self.weather_cam]


@dataclass
class SessionData:
    """Current session / lap timing."""
    mode: str = "STREET"
    session_time_s: float = 0.0
    lap_count: int = 0
    lap_times: List[float] = field(default_factory=list)
    best_lap: float = 0.0


@dataclass
class SystemState:
    """System status indicators."""
    logging: bool = False
    network: bool = True
    gps_fix: bool = True
    v1_connected: bool = False


@dataclass
class KistiFinding:
    """An insight generated by KiSTI analysis."""
    id: str = ""
    title: str = ""
    detail: str = ""
    severity: str = "info"  # info | warning | critical
    related_corners: List[str] = field(default_factory=list)


@dataclass
class VehicleState:
    """Complete vehicle telemetry snapshot."""
    corners: dict = field(default_factory=lambda: {
        "FL": CornerData(),
        "FR": CornerData(),
        "RL": CornerData(),
        "RR": CornerData(),
    })
    gps: GPSData = field(default_factory=GPSData)
    oil: OilPressureData = field(default_factory=OilPressureData)
    sensors: FrontSensorSuite = field(default_factory=FrontSensorSuite)
    session: SessionData = field(default_factory=SessionData)
    system: SystemState = field(default_factory=SystemState)
    radar: RadarState = field(default_factory=RadarState)
    findings: List[KistiFinding] = field(default_factory=list)
