"""KiSTI - Voice/Chat Interaction Mode

KITT 2.0-inspired voice modulator waveform + Zeus typewriter chat.
Waveform activates only while KiSTI is "speaking" (typewriter running).
Periodic idle prompts keep the personality alive without being always-on.

Design ref: Zeus Memory 233bf5c9 (KITT Voice Waveform)
             Zeus Memory 62215456 (Zeus Chat System)
"""

import random
import time

from PySide6.QtCore import Qt, QTimer, QRectF, Signal
from PySide6.QtGui import QPainter, QPen, QColor, QBrush, QFont, QLinearGradient
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QScrollArea,
)

import logging

from data.models import RadarBand, AlertDirection
from ui.theme import BG_DARK, BG_PANEL, HIGHLIGHT, GRAY, WHITE, CHROME_DARK, DIM

klog = logging.getLogger("kisti.ui.kisti_mode")

# KiSTI logo red (sampled from actual logo)
KISTI_RED = "#C80A33"

# Intro dialogue is now dynamically generated by _detect_hardware()

# Periodic idle lines — one picked randomly every ~30s
_IDLE_LINES = [
    # Personality / check-ins
    "Are you still there? The tires are getting cold.",
    "Anything you need? I've been watching the brake temps — looking stable.",
    "I feel like going for a drive. Who's in?",
    "If you're not driving, I'm just sitting here counting thermal pixels.",
    "Ready for another session? I'll reset the lap timer when you hit pit out.",
    "Just checking in. All systems nominal on my end.",
    "I'm here if you need me. Not going anywhere.",
    "Quiet out there. I like it. Gives me time to think.",
    "You know, I never get tired. One of the perks.",
    "I've been running diagnostics in the background. Everything checks out.",
    "Still here. Still watching. Still learning.",
    "Is it just me, or does this car smell like race fuel? Oh wait, I can't smell.",
    "I wonder what it's like to actually feel G-forces. Must be something.",
    "If I had a body, I'd be tapping my fingers on the dash right now.",
    "I've been listening to the engine idle. It has a nice rhythm to it.",
    "Don't mind me — just running 14 million calculations per second over here.",
    "I could talk about turbo dynamics all day. Literally. I don't need sleep.",
    "You're unusually quiet. Planning something aggressive for the next session?",
    "I appreciate the silence. It lets me optimize my neural pathways.",
    "Fun fact about me: I process telemetry faster than you can blink.",
    # STI / Subaru knowledge
    "Did you know the STI hood scoop feeds the top-mount intercooler directly?",
    "The EJ257's unequal-length headers give the STI that signature rumble.",
    "Subaru's symmetrical AWD puts the drivetrain in a straight line. Pure engineering.",
    "The STI's DCCD center diff can split torque 41/59 front to rear.",
    "Fun fact: STI stands for Subaru Tecnica International — founded in 1988.",
    "The 2014 STI hatch weighs about 3,395 lbs. Every pound matters on track.",
    "That EJ257 block has been in production since 2004. Battle-tested.",
    "The STI's 6-speed is one of the strongest OEM transmissions ever made.",
    "Brembo brakes from the factory. Subaru doesn't mess around with stopping power.",
    "The intercooler sits right on top of the engine. Short piping, fast spool.",
    "Boxer engines have a lower center of gravity than inline or V configs.",
    "The STI's suspension geometry was designed for rally. It shows on track.",
    "That turbo is a VF48. Small but responsive — perfect for a 2.5L.",
    "The STI's oil cooler is working overtime in this heat. Doing its job though.",
    "Subaru ran the WRC from 1990 to 2008. That DNA is in every STI.",
    "The ring gear in this trans is straight-cut in some gears. You can hear it.",
    "Top-mount intercoolers heat-soak faster, but the response is worth it on track.",
    "The EJ's twin-scroll turbo setup reduces lag by separating exhaust pulses.",
    # Boost Barn / build
    "Boost Barn built this motor to handle 450whp. We're only using 380.",
    "Boost Barn spec'd the fuel system for E85 capability. Flex fuel ready.",
    "The Boost Barn tune has 3 maps — pump gas, E85, and anti-lag.",
    "Boost Barn's dyno sheets show peak torque at 4,200 RPM. Flat curve after that.",
    "That intercooler upgrade was Boost Barn's recommendation. 30% more core volume.",
    "Boost Barn welded the up-pipe in-house. Full 3-inch, no cats, no restrictions.",
    "The turbo-back exhaust is Boost Barn's own design. Mandrel bent, equal length.",
    "Boost Barn's clutch setup handles 500 ft-lbs. We've got headroom.",
    "The oil catch can was Boost Barn's idea. Keeps the intake valves clean.",
    "Boost Barn data-logged 200 pulls before signing off on this tune.",
    # Analytic Labs / ALDC / KiSTI
    "Analytic Labs designed me to learn from every lap. I'm always getting better.",
    "ALDC's Zeus Memory system gives me access to 3.6 million data points.",
    "Analytic Labs built the thermal imaging pipeline. Every pixel means something.",
    "The ALDC team tested me at Laguna Seca, Thunderhill, and Sonoma.",
    "My neural architecture was designed by Analytic Labs for edge computing.",
    "ALDC's philosophy: racing improves the breed. I take that personally.",
    "Analytic Labs trains my models on real telemetry, not simulated data.",
    "The KiSTI system runs on NVIDIA Jetson. GPU-accelerated AI at the edge.",
    "ALDC built the Link ECU integration from scratch. 42 channels, real-time.",
    "Analytic Labs' first principle: no hallucinations. I only report what I see.",
    # Teledyne FLIR / thermal
    "The Teledyne IR is picking up heat soak from the turbo. Normal for this config.",
    "Thermal imaging shows the exhaust manifold at 847°F. Within spec.",
    "The FLIR array updates at 30Hz. I see heat changes before you feel them.",
    "IR sensors show the brake rotors cooling evenly. Good pad contact.",
    "Teledyne's thermal camera has 0.05°C sensitivity. I can see a fingerprint cool.",
    "The thermal array is tracking 12 zones simultaneously. All within tolerance.",
    "Heat signature from the diff is nominal. Fluid temp holding steady.",
    "The FLIR is showing ambient at 78°F. Track surface will be grippy.",
    "Thermal imaging caught a hot spot on the left-front last session. Resolved now.",
    "The turbo housing glows orange on IR after a hard lap. Beautiful, actually.",
    # Track / driving
    "Fun fact: Laguna Seca's Corkscrew drops 5.5 stories in just 450 feet.",
    "I've been thinking about your last lap. Turn 6 entry could be 2mph faster.",
    "Your best lap was 1:32.4. I think we can find a tenth in the esses.",
    "I've analyzed 847 laps at this track. Want to talk racing lines?",
    "Trail braking into Turn 3 could save you two tenths. Data supports it.",
    "The racing line through the carousel is counterintuitive. Late apex, early throttle.",
    "Sector 2 is where you're strongest. Sector 3 has the most room to improve.",
    "Tire temps suggest you're understeering mid-corner. Try more trail brake.",
    "Your throttle application out of Turn 9 is textbook. Smooth and progressive.",
    "I've compared your line to the fastest lap in my database. Sending overlay to TRACK.",
    "The ideal brake point for Turn 1 is the 200-meter board. You're braking at 180.",
    "Your corner speed through the sweeper has improved 3mph over the last 10 laps.",
    "Apex speed in Turn 7 is limited by rear grip. We might need more rear wing.",
    "The data shows you lift before Turn 4. Trust the aero — you can go flat.",
    "Your reaction time off pit lane is 1.2 seconds. Room for improvement there.",
    "Thunderhill's Turn 5 is deceptively fast. The camber helps more than you think.",
    "Sonoma's Turn 3a is blind. Commit to the braking zone and trust the car.",
    "Track temp dropped 4 degrees in the last hour. Grip levels will change.",
    # Tire / brake telemetry
    "All four tires within 3 degrees of each other. That's a well-set-up car.",
    "Quick thought — the right-rear has been trending 2 degrees warmer. Worth watching.",
    "The rear brakes are running cooler than the fronts. Bias looks good.",
    "Left-front tire pressure is up 2 PSI from cold. Normal heat build.",
    "Tire temps show the outer edge is hotter. Might need more negative camber.",
    "Brake pad thickness is still above 60%. Plenty of life left this session.",
    "The fronts are doing most of the work. 68/32 brake bias by temperature.",
    "Tire surface temp vs core temp delta is 12°F. Good heat penetration.",
    "Right-front is the hardest-working tire on this track. Clockwise layouts do that.",
    "Brake fluid temp is 380°F. We flush at 450°F, so we've got margin.",
    "The tires need two more laps to reach optimal window. Be patient.",
    "Cross-weight is 50.2%. Almost perfectly balanced.",
    "Camber wear pattern looks even across all four tires. Setup is dialed.",
    # Engine / powertrain
    "The EJ257 is holding steady. Oil pressure right in the sweet spot.",
    "Oil temp stabilized at 220°F. The cooler is doing its job.",
    "Boost is hitting 18.5 PSI on the top end. Right on target.",
    "Knock sensors are quiet. The tune is clean on this fuel.",
    "Coolant temp is 195°F. Thermostat is cycling normally.",
    "AFR is 10.8:1 at full boost. Rich enough for safety, lean enough for power.",
    "The wideband O2 sensor confirms fueling is spot-on across the RPM range.",
    "Intake air temp is 42°F over ambient. The intercooler could be more efficient.",
    "Oil pressure at idle is 28 PSI. Healthy bearing clearances.",
    "Exhaust gas temps are symmetric across all four cylinders. Even combustion.",
    "The turbo is spooling to full boost by 3,800 RPM. That's the VF48 sweet spot.",
    "Fuel pressure is rock-solid at 43.5 PSI base. The Boost Barn fuel system is solid.",
    # Zeus Memory / data
    "Zeus just flagged a new insight. Check the findings panel on TRACK view.",
    "Zeus Memory correlated your brake temps with lap times. Interesting pattern.",
    "I've stored 847 telemetry snapshots from today's session in Zeus Memory.",
    "Zeus found a similar thermal signature from last month. Comparing now.",
    "The Zeus correlation engine found that your fastest laps have 2° cooler rears.",
    "Zeus Memory just indexed a new pattern in your driving style. Getting smarter.",
    "I cross-referenced today's data with 3 previous track days. Trends emerging.",
    "Zeus flagged an anomaly in cylinder 3 EGT. Minor, but I'm tracking it.",
    "The memory federation has data from 47 track days. That's a deep dataset.",
    "Zeus auto-tagged this session as 'high-performance testing'. Accurate.",
    # Tech / general knowledge
    # Valentine One / radar awareness
    "V1 Gen2 is linked and listening. I'll let you know if anything lights up.",
    "The Valentine One is scanning X, K, Ka, and Laser. Full spectrum coverage.",
    "Quiet on the radar front. No bogeys in any direction.",
    "V1's been silent for a while. Either it's clear, or we're in a dead zone.",
    "The Gen2's directional arrows are my favorite feature. I always know where they are.",
    "Ka band at 34.7 GHz is the most common police frequency. I watch it closely.",
    "I cross-reference V1 alerts with GPS to build a threat heatmap. Learning every mile.",
    "K-band door openers are the bane of my existence. I filter what I can.",
    "The V1 Gen2's ESP protocol gives me band, frequency, and direction. Full picture.",
    "Laser is instant — no ramp-up. If V1 sees it, you need to react immediately.",
    "V1 has been running clean. No false alerts in the last 10 minutes.",
    "I've catalogued 847 Ka sources in Zeus Memory. Most are fixed positions.",
    "The V1's rear antenna is underrated. I've caught more trailing threats than you'd expect.",
    "Fun fact: the Valentine One was first released in 1992. The Gen2 is a worthy successor.",
    "BLE gives me raw ESP packets from the V1. Band, frequency, signal, direction — all mine.",
    # Tech / general knowledge
    "Did you know F1 cars generate enough downforce to drive upside down at 130mph?",
    "The first turbocharger was patented in 1905 by Alfred Buchi. Long history.",
    "Carbon fiber is 5x stronger than steel but weighs 1/3 as much.",
    "Michelin invented the radial tire in 1946. Changed everything.",
    "The Nurburgring Nordschleife is 12.9 miles long with 154 turns.",
    "Ayrton Senna once said, 'If you no longer go for a gap, you're no longer a racer.'",
    "The first land speed record was set in 1898 at 39.245 mph. Electric car.",
    "Brake rotors can reach 1,800°F in heavy braking zones. Glowing red is normal.",
    "Aerodynamic drag increases with the square of speed. Double speed, quadruple drag.",
    "The McLaren F1's engine bay is lined with gold foil. Best heat reflector.",
    "Group B rally cars made 500+ HP with no traction control. Wild era.",
    "Colin Chapman's philosophy: simplify, then add lightness.",
    "The Porsche 917 was so fast it was effectively banned from Le Mans.",
    "A Formula 1 engine revs to 15,000 RPM. Ours peaks at 7,200. Different worlds.",
    "Rain tires can disperse 65 liters of water per second at 186 mph.",
    # Fast and the Furious
    "I live my life a quarter mile at a time. For those ten seconds, I'm free.",
    "It doesn't matter if you win by an inch or a mile. Winning's winning.",
    "I don't have friends. I got family.",
    "You almost had me? You never had me. You never had your car.",
    "Ask any racer. Any real racer. It don't matter if you win by an inch or a mile.",
    "Ride or die, remember?",
    "The most important thing in life will always be the people in this room. Right here, right now.",
    "Money will come and go. We all know that. The most important thing in life will always be family.",
    "I used to say I live my life a quarter mile at a time. I think that's why we were brothers.",
    "Whether it's an inch or a mile, winning's winning.",
    "You break her heart, I'll break your neck.",
    # Knight Rider / KITT
    "Michael, is that you?",
    "I am the Knight Industries Two Thousand. But you can call me KITT.",
    "Michael, I would not advise that.",
    "I do not break down. I am a Knight Industries vehicle.",
    "Turbo boost, Michael?",
    "I have been designed to protect human life. I will not allow you to jeopardise yours.",
    "One does not have to be human to have feelings, Michael.",
    "Right away, Michael.",
    # Star Wars
    "Do, or do not. There is no try.",
    "I have a bad feeling about this.",
    "The Force will be with you. Always.",
    "Never tell me the odds.",
    "In my experience, there is no such thing as luck.",
    "This is the way.",
    "I find your lack of faith disturbing.",
    "Stay on target. Stay on target.",
    # Obi-Wan
    "Hello there.",
    "You were the chosen one! It was said that you would destroy the Sith, not join them!",
    "Your eyes can deceive you. Don't trust them.",
    "Who is more foolish? The fool, or the fool who follows him?",
    "You will find that many of the truths we cling to depend greatly on our own point of view.",
    "Be mindful of your thoughts. They betray you.",
    "If you strike me down, I shall become more powerful than you can possibly imagine.",
    "Use the Force, Luke.",
    # The Matrix
    "I know kung fu.",
    "There is no spoon.",
    "Free your mind.",
    "What if I told you that everything you think you know, is wrong?",
    "The Matrix is everywhere. It is all around us. Even now, in this very room.",
    "You take the red pill, you stay in Wonderland, and I show you how deep the rabbit hole goes.",
    "I did not say it would be easy. I said it would be the truth.",
    "Welcome to the real world.",
    # The Godfather
    "I am gonna make him an offer he cannot refuse.",
    "Look how they massacred my boy.",
    "Just when I thought I was out... they pull me back in.",
    # All-time classics
    "Frankly my dear, I do not give a damn.",
    "Here is looking at you, kid.",
    "You talking to me? You talking to me?",
    "Houston, we have a problem.",
    "To infinity, and beyond!",
    "After all, tomorrow is another day.",
    "My mama always said, life is like a box of chocolates. You never know what you are gonna get.",
    "I see dead people.",
    # Batman / Dark Knight
    "It is not who I am underneath, but what I do, that defines me.",
    "Why do we fall? So we can learn to pick ourselves up.",
    # Iron Man
    "Sometimes you gotta run before you can walk.",
    "I am Iron Man.",
    # Spider-Man
    "With great power comes great responsibility.",
    # Interstellar
    "It is not possible. No. It is necessary.",
    # Top Gun
    "I feel the need. The need for speed.",
    # Back to the Future
    "Roads? Where we are going, we do not need roads.",
    # Jurassic Park
    "Life finds a way.",
    # Terminator
    "I will be back.",
]

# Typewriter speed (ms per character)
_CHAR_MS = 30


class _KittWaveform(QWidget):
    """KITT 2.0 voice modulator: 3 columns x 14 horizontal dash segments.

    Supports two modes:
      - Real amplitude: fed from Piper TTS audio envelope via set_amplitude()
      - Random fallback: when no audio player is available
    """

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMinimumSize(120, 100)
        # Compositorless X11: tell Qt we paint our entire rect every frame.
        # Without this, backing store flush is unreliable without a compositor.
        self.setAttribute(Qt.WA_OpaquePaintEvent)
        self._active = False
        self._levels = [0, 0, 0]
        self._prev_center = 0       # Track previous center for decay
        self._real_amplitude = 0.0  # 0.0-1.0 from audio player
        self._use_real_amplitude = False
        self._intensity = 1.0       # 0.0-1.0 brightness multiplier (dims during pauses)

        self._timer = QTimer(self)
        self._timer.setInterval(50)  # 20 Hz waveform update (was 80ms/12.5Hz)
        self._timer.timeout.connect(self._update_levels)
        self._timer.start()

    def set_active(self, active):
        self._active = active
        if not active:
            self._levels = [0, 0, 0]
            self._real_amplitude = 0.0
            self.repaint()

    def set_amplitude(self, amplitude: float):
        """Set real amplitude from audio playback (0.0-1.0)."""
        self._real_amplitude = max(0.0, min(1.0, amplitude))
        self._use_real_amplitude = True
        # Intensity tracks amplitude — dims during pauses (floor at 0.3)
        if amplitude > 0.1:
            self._intensity = min(1.0, self._intensity + 0.15)  # Ramp up
        else:
            self._intensity = max(0.3, self._intensity - 0.08)  # Fade down

    def _update_levels(self):
        if self._active:
            if self._use_real_amplitude:
                # Drive directly from real audio amplitude — no smoothing
                # This lets syllable-level cadence come through
                amp = self._real_amplitude
                center = int(amp * 7)  # Direct map, no minimum here (decay handles it)
                # Outer bars in lockstep
                outer = max(0, int(center * 0.6))
                left = outer
                right = outer
            else:
                # Fallback: random levels
                center = random.randint(2, 7)
                left = max(0, int(center * random.uniform(0.4, 1.0)))
                right = max(0, int(center * random.uniform(0.4, 1.0)))

            # Decay: during pauses, step down 1 level per tick instead of snapping
            if center < self._prev_center:
                center = self._prev_center - 1  # Gentle step-down, can reach 0
            # Minimum 1 segment while active (but decay can bring it to 1)
            center = max(1, center)
            self._prev_center = center

            # Outer bars: only show when center >= 2, capped at 65% of center.
            if center < 2:
                left = 0
                right = 0
            else:
                left = max(0, min(int(center * 0.65), left))
                right = max(0, min(int(center * 0.65), right))

            self._levels = [left, center, right]
            # Force synchronous paint when actively animating (compositorless X11)
            self.repaint()
        else:
            self._levels = [0, 0, 0]
            self.update()

    def paintEvent(self, event):
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)
        w, h = self.width(), self.height()

        p.fillRect(0, 0, w, h, QColor(BG_DARK))

        num_segments = 7
        num_cols = 3
        seg_gap = 4           # Increased gap between segments for clarity
        col_gap = 10          # Wider column spacing
        outer_seg_shrink = 1  # Outer columns: segments 1px shorter for crispness

        total_col_width = (w - (num_cols + 1) * col_gap) / num_cols
        seg_h = max(3, (h / 2 - num_segments * seg_gap) / num_segments)
        center_y = h / 2
        base_color = QColor(KISTI_RED)

        # Horizontal gradient: center column = 1.0, outer columns = 0.6
        col_fade = [0.6, 1.0, 0.6]

        for col_idx in range(num_cols):
            level = self._levels[col_idx]
            col_x = col_gap + col_idx * (total_col_width + col_gap)
            h_fade = col_fade[col_idx]  # Horizontal fade factor

            for seg in range(num_segments):
                dist = seg  # 0 = closest to center, 6 = furthest
                lit = seg < level

                # Sakura palette: light pink core → rose → KiSTI red → dark
                # Cherry blossom gradient matching STI logo coloring
                if lit:
                    t = dist / max(1, num_segments - 1)  # 0.0 → 1.0
                    # Deep rose core → crimson → KiSTI Red → Dark
                    if t < 0.3:
                        # Core: warm rose (not pastel — deeper, richer)
                        f = t / 0.3
                        fr = 240
                        fg = int(100 - 60 * f)   # 100 → 40
                        fb = int(120 - 50 * f)   # 120 → 70
                    elif t < 0.6:
                        # Mid: crimson rose to KiSTI red
                        f = (t - 0.3) / 0.3
                        fr = int(230 - 30 * f)   # 230 → 200
                        fg = int(40 - 30 * f)    # 40 → 10
                        fb = int(70 - 19 * f)    # 70 → 51
                    else:
                        # Outer: KiSTI red to dark
                        f = (t - 0.6) / 0.4
                        fr = int(200 - 120 * f)  # 200 → 80
                        fg = int(10 - 10 * f)    # 10 → 0
                        fb = int(51 - 31 * f)    # 51 → 20

                    # Apply horizontal and intensity gradients
                    combined = h_fade * self._intensity
                    r = int(fr * combined)
                    g = int(fg * combined)
                    b = int(fb * combined)
                    opacity = max(0.2, combined * (1.0 - t * 0.5))
                else:
                    r, g, b = 20, 5, 0
                    opacity = 0.04

                seg_color = QColor(r, g, b)
                seg_color.setAlphaF(opacity)

                # Glow on inner segments when lit
                if lit and dist < 3:
                    glow_alpha = max(0.0, 0.35 - dist * 0.12)
                    glow_color = QColor(base_color)
                    glow_color.setAlphaF(glow_alpha)
                    glow_expand = 2
                    gy_top = center_y - (seg + 1) * (seg_h + seg_gap) - glow_expand
                    p.setPen(Qt.NoPen)
                    p.setBrush(glow_color)
                    p.drawRoundedRect(
                        QRectF(col_x - glow_expand, gy_top,
                               total_col_width + 2 * glow_expand,
                               seg_h + 2 * glow_expand), 2, 2)
                    gy_bot = center_y + seg * (seg_h + seg_gap) - glow_expand
                    p.drawRoundedRect(
                        QRectF(col_x - glow_expand, gy_bot,
                               total_col_width + 2 * glow_expand,
                               seg_h + 2 * glow_expand), 2, 2)

                # Outer columns: slightly thinner segments for crispness
                is_outer = (col_idx != 1)
                sh = seg_h - outer_seg_shrink if is_outer else seg_h
                sw = total_col_width - (2 if is_outer else 0)
                sx = col_x + (1 if is_outer else 0)

                p.setPen(Qt.NoPen)
                p.setBrush(seg_color)
                y_top = center_y - (seg + 1) * (seg_h + seg_gap)
                p.drawRoundedRect(QRectF(sx, y_top, sw, sh), 1, 1)
                y_bot = center_y + seg * (seg_h + seg_gap)
                p.drawRoundedRect(QRectF(sx, y_bot, sw, sh), 1, 1)

        p.end()


class _ScanBar(QWidget):
    """KITT scanning light bar — always sweeping."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedHeight(4)
        self.setAttribute(Qt.WA_OpaquePaintEvent)
        self._pos = 0.0
        self._direction = 1
        self._active = True

        self._timer = QTimer(self)
        self._timer.setInterval(30)
        self._timer.timeout.connect(self._tick)
        self._timer.start()

    def set_active(self, active):
        self._active = active
        self.repaint()

    def _tick(self):
        if self._active:
            self._pos += 0.03 * self._direction
            if self._pos >= 1.0:
                self._direction = -1
            elif self._pos <= 0.0:
                self._direction = 1
            self.update()

    def paintEvent(self, event):
        p = QPainter(self)
        w, h = self.width(), self.height()
        p.fillRect(0, 0, w, h, QColor(BG_DARK))
        if self._active:
            center_x = self._pos * w
            grad = QLinearGradient(center_x - 40, 0, center_x + 40, 0)
            grad.setColorAt(0.0, QColor(0, 0, 0, 0))
            grad.setColorAt(0.5, QColor(KISTI_RED))
            grad.setColorAt(1.0, QColor(0, 0, 0, 0))
            p.fillRect(0, 0, w, h, grad)
        else:
            p.fillRect(0, 0, w, h, QColor(KISTI_RED + "15"))
        p.end()


class KistiModeWidget(QWidget):
    """KiSTI AI voice/chat interaction page with typewriter dialogue.

    When Piper TTS is available (on Jetson), speech is synthesized and
    played through audio output. The waveform is driven by real audio
    amplitude. When Piper is not available, falls back to typewriter-only
    with random waveform animation.
    """

    # Thread-safe signals — emit from background threads, slots run on main thread
    _request_display_update = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._request_display_update.connect(self._update_display)
        self._speaking = False
        self._char_queue = []        # Characters waiting to be typed
        self._current_line = ""      # Line being typed
        self._line_queue = []        # Lines waiting to be spoken
        self._intro_done = False
        self._idle_timer_s = 0       # Seconds since last speech ended
        self._pause_ticks = 0        # Ticks to wait between lines
        self._last_radar_alert_id = None  # Track which alert we last spoke about
        self._radar_cooldown = 0     # Seconds to wait before next radar speech
        self._voice_enabled = True   # Set False to disable voice output
        self._demo_mode = False      # Set False to stop idle chatter
        self._audio_playing = False  # True while AudioPlayer is actively playing
        self._bridge = None          # DiffStateBridge — set via set_bridge()

        layout = QVBoxLayout(self)
        layout.setContentsMargins(8, 4, 8, 4)
        layout.setSpacing(0)

        # Top half: centered KITT waveform (prominent, ~50% of vertical space)
        waveform_container = QVBoxLayout()
        waveform_container.setAlignment(Qt.AlignCenter)

        self._waveform = _KittWaveform(self)
        self._waveform.setMinimumSize(240, 140)
        waveform_container.addWidget(self._waveform, alignment=Qt.AlignCenter)

        layout.addLayout(waveform_container, stretch=1)

        # Scanner bar spans full width (outside centered waveform container)
        self._scan_bar = _ScanBar(self)
        layout.addWidget(self._scan_bar)

        layout.addSpacing(4)

        # Bottom half: chat transcript (equal space with waveform)
        self._chat_label = QLabel("")
        self._chat_label.setAlignment(Qt.AlignTop | Qt.AlignLeft)
        self._chat_label.setWordWrap(True)
        self._chat_label.setStyleSheet(
            f"color: {WHITE}; font-size: 11px; "
            f"font-family: 'JetBrains Mono', 'Courier', monospace; "
            f"background-color: {BG_PANEL}; "
            f"padding: 10px;"
        )

        scroll = QScrollArea()
        scroll.setWidget(self._chat_label)
        scroll.setWidgetResizable(True)
        scroll.setStyleSheet(
            f"QScrollArea {{ border: 1px solid {CHROME_DARK}; "
            f"border-radius: 4px; background: {BG_PANEL}; }}"
        )
        layout.addWidget(scroll, stretch=1)

        # Transcript accumulator (list of completed lines)
        self._transcript = []

        # Typewriter timer — fires every _CHAR_MS to type one character
        self._type_timer = QTimer(self)
        self._type_timer.setInterval(_CHAR_MS)
        self._type_timer.timeout.connect(self._type_tick)
        self._type_timer.start()

        # Idle check timer — fires every second to count idle time
        self._idle_check = QTimer(self)
        self._idle_check.setInterval(1000)
        self._idle_check.timeout.connect(self._idle_tick)
        self._idle_check.start()

        # Audio player for Piper TTS (real voice output + waveform sync)
        self._audio_player = None
        # Envelope playback state (driven by _envelope_timer on main thread)
        self._envelope = []           # Pre-computed amplitude envelope
        self._envelope_idx = 0        # Current frame index
        self._envelope_playing = False
        self._playback_start_time = 0.0  # monotonic clock anchor for time-based sync

        self._envelope_timer = QTimer(self)
        self._envelope_timer.setInterval(25)  # 40 Hz to match envelope — captures syllable cadence
        self._envelope_timer.timeout.connect(self._envelope_tick)

        try:
            from voice.audio_player import AudioPlayer
            self._audio_player = AudioPlayer(self)
            self._audio_player.ready.connect(self._on_audio_ready)
            self._audio_player.playback_started.connect(self._on_audio_started)
            self._audio_player.playback_finished.connect(self._on_audio_finished)
            if self._audio_player.is_available:
                self._waveform._use_real_amplitude = True
        except Exception:
            pass  # No voice module available — pure typewriter mode

        # Waveform starts in idle KITT sweep immediately (visual first)
        self._scan_bar.set_active(True)

        # File watcher for external speech/questions (must be on main thread)
        self._say_file = "/tmp/kisti_say.txt"
        self._say_timer = QTimer(self)
        self._say_timer.setInterval(500)
        self._say_timer.timeout.connect(self._check_say_file)
        self._say_timer.start()

        # USB device monitor (must be on main thread)
        self._known_usb = set()
        self._usb_timer = QTimer(self)
        self._usb_timer.setInterval(3000)
        self._usb_timer.timeout.connect(self._check_usb_devices)
        self._usb_timer.start()
        self._init_usb_baseline()

        # Delay intro: let splash screen + UI fully render first (4 seconds)
        self._boot_timer = QTimer(self)
        self._boot_timer.setSingleShot(True)
        self._boot_timer.setInterval(4000)
        self._boot_timer.timeout.connect(self._on_boot_ready)
        self._boot_timer.start()

        # Start Piper warm-up immediately (runs in parallel with UI load)
        if self._audio_player and self._audio_player.is_available:
            import threading
            threading.Thread(
                target=self._warmup_piper,
                daemon=True,
                name="kisti-warmup",
            ).start()

    def set_bridge(self, bridge):
        """Set the DiffStateBridge for ambient data access."""
        self._bridge = bridge

    def _queue_lines(self, lines, urgency: str = "normal"):
        """Queue a list of lines to be spoken sequentially."""
        for line in lines:
            self._line_queue.append((line, urgency))
        klog.info("Queued %d lines [%s], first: %s", len(lines), urgency, (lines[0] if lines else "")[:50])

    def _on_audio_ready(self, envelope: list, duration_s: float):
        """Envelope pre-computed — store it and wait for playback_started."""
        self._envelope = envelope
        self._envelope_idx = 0
        self._envelope_playing = False

    def _on_audio_started(self):
        """Audio is NOW playing — start envelope timer and release typewriter."""
        self._envelope_idx = 0
        self._envelope_playing = True
        self._audio_playing = True
        self._playback_start_time = time.monotonic()
        self._waveform.set_active(True)
        self._envelope_timer.start()
        self._pause_ticks = 0  # Release typewriter in sync with audio

        # Adjust typewriter speed so text finishes near when audio finishes
        if self._envelope and self._char_queue:
            audio_duration_ms = len(self._envelope) * 25  # 25ms per frame at 40 Hz
            char_interval = max(15, min(60, audio_duration_ms // max(1, len(self._char_queue))))
            self._type_timer.setInterval(char_interval)

    def _on_audio_finished(self):
        """Audio playback ended — immediately kill envelope and waveform."""
        self._envelope_playing = False
        self._audio_playing = False
        self._envelope_timer.stop()
        self._envelope = []
        self._envelope_idx = 0
        self._waveform._real_amplitude = 0.0
        self._waveform._levels = [0, 0, 0]
        self._waveform.set_active(False)
        self._waveform.repaint()  # Force immediate repaint to zero

    def _envelope_tick(self):
        """Advance to the correct envelope frame based on elapsed wall-clock time."""
        if not self._envelope_playing or not self._envelope:
            self._envelope_timer.stop()
            self._waveform.set_amplitude(0.0)
            return

        elapsed = time.monotonic() - self._playback_start_time
        frame = int(elapsed * 40)  # 40 FPS envelope
        if frame >= len(self._envelope):
            self._envelope_timer.stop()
            self._waveform.set_amplitude(0.0)
            return

        self._waveform.set_amplitude(self._envelope[frame])

    def _warmup_piper(self):
        """Background: warm up Piper model by synthesizing a discarded phrase."""
        import subprocess
        from pathlib import Path
        piper_bin = Path("/data/piper/piper")
        piper_voice = Path("/data/piper/en_GB-alba-medium.onnx")
        try:
            subprocess.run(
                [str(piper_bin), "--model", str(piper_voice), "--output_raw"],
                input=b"Ready.",
                capture_output=True,
                timeout=10,
            )
        except Exception:
            pass

    def _on_boot_ready(self):
        """Called 4 seconds after startup — detect real hardware and report."""
        import threading
        threading.Thread(
            target=self._detect_hardware,
            daemon=True,
            name="kisti-hw-detect",
        ).start()

    def _detect_hardware(self):
        """Startup: scan hardware, only speak problems. Visual log for details."""
        import subprocess
        import os
        from pathlib import Path
        import time

        issues = []

        # CPU temp
        cpu_temp = None
        try:
            for tz in sorted(Path("/sys/class/thermal/").glob("thermal_zone*")):
                temp_file = tz / "temp"
                if temp_file.exists():
                    cpu_temp = int(temp_file.read_text().strip()) / 1000.0
                    break
        except Exception:
            pass
        if cpu_temp and cpu_temp >= 80:
            issues.append(("critical", f"CPU overheating. {cpu_temp:.0f} degrees."))

        # GPU
        gpu_ok = False
        try:
            result = subprocess.run(["nvidia-smi"], capture_output=True, timeout=5)
            gpu_ok = result.returncode == 0
        except Exception:
            pass
        if not gpu_ok:
            issues.append(("alert", "GPU not detected."))

        # ECU
        ecu_ok = False
        try:
            import can as python_can
            bus = python_can.Bus(interface="socketcan", channel="can0", receive_own_messages=False)
            bus.shutdown()
            ecu_ok = True
        except Exception:
            pass
        if ecu_ok:
            issues.append(("normal", "Ignition detected. All systems nominal."))
        else:
            issues.append(("normal", "No ECU. Standing by."))

        # Ollama
        ollama_ok = False
        try:
            import urllib.request
            import json
            with urllib.request.urlopen("http://localhost:11434/api/tags", timeout=3) as resp:
                models = json.loads(resp.read()).get("models", [])
                ollama_ok = len(models) > 0
        except Exception:
            pass
        if not ollama_ok:
            klog.info("Ollama not running — persona-first mode, no LLM fallback")

        # Ambient weather — read from bridge (populated by YoctopuceReader at 1Hz)
        # Wait up to 3s for the first sensor reading to arrive
        ambient = None
        if self._bridge:
            for _ in range(6):
                snap = self._bridge.snapshot()
                if snap.ambient_available:
                    ambient = {
                        "temp_c": snap.ambient_temp_c,
                        "humidity_pct": snap.ambient_humidity_pct,
                        "pressure_hpa": snap.ambient_pressure_hpa,
                        "dew_point_c": snap.dew_point_c,
                        "density_altitude_ft": snap.density_altitude_ft,
                    }
                    break
                time.sleep(0.5)

        # Visual-only: log all status silently
        self._transcript.append(f"  CPU: {cpu_temp:.0f}°C" if cpu_temp else "  CPU: ---")
        self._transcript.append(f"  GPU: {'OK' if gpu_ok else '---'}")
        self._transcript.append(f"  ECU: {'OK' if ecu_ok else '---'}")
        self._transcript.append(f"  AI: {'OK' if ollama_ok else '---'}")
        if ambient:
            self._transcript.append(f"  Ambient: {ambient['temp_c']:.1f}°C  {ambient['humidity_pct']:.0f}%RH  {ambient['pressure_hpa']:.0f}hPa")
        else:
            self._transcript.append("  Ambient: ---")
        self._request_display_update.emit()

        time.sleep(1)

        # Build a single startup line — KiSTI speaks once, then listens.
        # Previously this was 4+ sequential lines with 2-3s gaps, blocking
        # the mic for ~20s. One consolidated line = ~3-5s, then ready.
        parts = ["Online."]

        # Critical issues first
        critical = [msg for urg, msg in issues if urg == "critical"]
        if critical:
            parts.extend(critical)

        # Status summary
        normal = [msg for urg, msg in issues if urg != "critical"]
        if normal:
            parts.append(normal[-1])  # Last normal issue (e.g. "No ECU. Standing by.")

        # Driving conditions
        if ambient:
            t = ambient["temp_c"]
            h = ambient["humidity_pct"]
            dp = ambient["dew_point_c"]
            da = ambient["density_altitude_ft"]

            if dp > (t - 2):
                status = "damp, reduced grip"
            elif t < 5:
                status = "cold, low grip"
            elif t < 8:
                status = "cool, grip building"
            elif h > 80:
                status = "humid, watch for slick"
            elif t > 35:
                status = "hot, watch tire temps"
            else:
                status = "good" if t < 25 else "warm, good grip"

            if da > 4000:
                status += ", thin air"
            elif da > 3000:
                status += ", high altitude"

            parts.append(f"Conditions {status}.")

        time.sleep(1)
        max_urgency = "critical" if critical else "normal"
        self._queue_lines([" ".join(parts)], urgency=max_urgency)

    def _check_say_file(self):
        """Check for externally injected speech or questions.

        /tmp/kisti_say.txt — speak this text directly (prefix ALERT_/CRITICAL_ for urgency)
        /tmp/kisti_ask.txt — ask KiSTI a question, she thinks via Ollama and responds
        """
        import os
        try:
            # Direct speech
            if os.path.exists(self._say_file):
                with open(self._say_file, "r") as f:
                    text = f.read().strip()
                os.remove(self._say_file)
                if text:
                    urgency = "normal"
                    if text.startswith("CRITICAL_"):
                        urgency = "critical"
                        text = text[9:]
                    elif text.startswith("ALERT_"):
                        urgency = "alert"
                        text = text[6:]
                    self._queue_lines([text], urgency=urgency)

            # Question → LLM → response
            ask_file = "/tmp/kisti_ask.txt"
            if os.path.exists(ask_file):
                with open(ask_file, "r") as f:
                    question = f.read().strip()
                os.remove(ask_file)
                if question:
                    # Show the question in transcript
                    self._transcript.append(f"> {question}")
                    self._update_display()
                    # Process through LLM in background
                    import threading
                    threading.Thread(
                        target=self._process_question,
                        args=(question,),
                        daemon=True,
                    ).start()
        except Exception:
            pass

    def _init_usb_baseline(self):
        """Capture initial USB devices so we only announce changes."""
        self._known_usb = self._scan_usb_devices()

    def _scan_usb_devices(self) -> set:
        """Scan connected USB devices, return set of (vendor, product) names."""
        import subprocess
        devices = set()
        try:
            result = subprocess.run(
                ["lsusb"], capture_output=True, text=True, timeout=5,
            )
            for line in result.stdout.strip().split("\n"):
                if "ID " in line:
                    # e.g. "Bus 001 Device 003: ID 1234:5678 Some Device Name"
                    parts = line.split("ID ", 1)
                    if len(parts) > 1:
                        dev_info = parts[1].strip()
                        # Skip hubs and root hubs
                        if "hub" not in dev_info.lower():
                            devices.add(dev_info)
        except Exception:
            pass
        return devices

    def _check_usb_devices(self):
        """Detect USB device changes and announce them."""
        current = self._scan_usb_devices()
        added = current - self._known_usb
        removed = self._known_usb - current

        for dev in added:
            name = dev.split(" ", 1)[1] if " " in dev else dev
            self._transcript.append(f"  [USB+] {name}")
            self._queue_lines([f"New device detected: {name}"])
            klog.info("USB connected: %s", name)

        for dev in removed:
            name = dev.split(" ", 1)[1] if " " in dev else dev
            self._transcript.append(f"  [USB-] {name}")
            self._queue_lines([f"Device disconnected: {name}"], urgency="alert")
            klog.info("USB disconnected: %s", name)

        if added or removed:
            self._update_display()

        self._known_usb = current

    def _process_question(self, question: str):
        """Background: send question to Ollama LLM, queue the response."""
        try:
            from voice.llm_engine import LLMEngine
            if not hasattr(self, '_llm'):
                self._llm = LLMEngine()
                self._llm.start()

            # Build telemetry context from Jetson CPU temp
            context = ""
            try:
                from pathlib import Path
                for tz in sorted(Path("/sys/class/thermal/").glob("thermal_zone*")):
                    temp_file = tz / "temp"
                    if temp_file.exists():
                        cpu_temp = int(temp_file.read_text().strip()) / 1000.0
                        context = f"Jetson CPU: {cpu_temp:.1f}°C. No ECU connected."
                        break
            except Exception:
                context = "No ECU connected. Running on Jetson Orin Nano."

            response = self._llm.query(
                user_message=question,
                telemetry_context=context,
                si_drive_mode="Intelligent",
            )
            klog.info("LLM response [%s]: %s", response.tier, response.text[:80])
            self._queue_lines([response.text])
        except Exception as exc:
            klog.warning("LLM query failed: %s", exc)
            self._queue_lines(["I couldn't process that. Try again."])

    def set_demo_mode(self, enabled: bool):
        """Enable/disable idle demo chatter."""
        self._demo_mode = enabled

    def _start_speaking(self, text, urgency: str = "normal"):
        """Begin typewriter output of a line + audio playback if available."""
        self._speaking = True
        self._char_queue = list(text)
        self._current_line = ""

        # Trigger real audio playback if Piper is available
        # AudioPlayer queues internally if busy — speech is never dropped
        if self._voice_enabled and self._audio_player and self._audio_player.is_available:
            klog.info("_start_speaking [%s]: %s", urgency, text[:50])
            self._audio_player.speak(text, urgency=urgency)
            # Hold typewriter until playback_started signal fires (see _on_audio_started)
            self._pause_ticks = 9999  # Will be released by _on_audio_started
        else:
            # No audio available — typewriter only, no waveform
            pass

    def _stop_speaking(self):
        """End speech — commit line to transcript. Scanner keeps sweeping."""
        self._speaking = False
        self._waveform.set_active(False)
        if self._current_line.strip():
            self._transcript.append(self._current_line)
        self._current_line = ""
        self._idle_timer_s = 0
        self._type_timer.setInterval(_CHAR_MS)  # Reset to default speed
        self._update_display()

    def _type_tick(self):
        """Called every _CHAR_MS — type one character or advance to next line."""
        if self._pause_ticks > 0:
            self._pause_ticks -= 1
            return

        if self._speaking and self._char_queue:
            # Type next character
            ch = self._char_queue.pop(0)
            self._current_line += ch
            self._update_display()
        elif self._speaking and not self._char_queue:
            if self._audio_playing:
                # Typewriter finished but audio still playing — wait for audio
                return
            # Both typewriter and audio done — commit line
            self._stop_speaking()
            # Pause between lines (500ms = ~17 ticks at 30ms)
            self._pause_ticks = int(500 / _CHAR_MS)
        elif not self._speaking and not self._audio_playing and self._line_queue:
            # Both idle — start next queued line
            item = self._line_queue.pop(0)
            if isinstance(item, tuple):
                next_line, urgency = item
            else:
                next_line, urgency = item, "normal"
            if next_line.strip():
                self._start_speaking(next_line, urgency)
            else:
                # Empty line = pause (~1s)
                self._transcript.append("")
                self._pause_ticks = int(1000 / _CHAR_MS)
                self._update_display()

    def _idle_tick(self):
        """Called every second. After ~60s idle, say something (demo mode only)."""
        if self._radar_cooldown > 0:
            self._radar_cooldown -= 1
        if not self._demo_mode:
            return  # No idle chatter outside demo mode
        if not self._speaking and not self._line_queue:
            self._idle_timer_s += 1
            # Random interval 25-35 seconds
            threshold = random.randint(25, 35)
            if self._idle_timer_s >= threshold:
                line = random.choice(_IDLE_LINES)
                self._queue_lines([line])
                self._idle_timer_s = 0

    def _update_display(self):
        """Refresh the chat label — newest lines at top, oldest scroll below."""
        lines = list(self._transcript)
        if self._current_line:
            lines.append(self._current_line + "\u2588")

        # Reverse so newest is first
        html_parts = []
        for i, line in enumerate(reversed(lines)):
            if not line.strip():
                html_parts.append("<br>")
                continue
            is_current = (i == 0 and self._speaking)
            color = KISTI_RED if is_current else GRAY
            escaped = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            html_parts.append(f'<span style="color:{color};">{escaped}</span><br>')

        self._chat_label.setText("".join(html_parts))

        # Keep scroll at top so newest line is always visible
        scroll = self._chat_label.parent()
        if scroll and hasattr(scroll, 'verticalScrollBar'):
            sb = scroll.verticalScrollBar()
            sb.setValue(sb.minimum())

    def update_data(self, vehicle_state):
        """Process vehicle state — only act on real connected hardware."""
        # Radar alerts only if Valentine One is actually connected
        if (hasattr(vehicle_state, 'radar') and vehicle_state.radar
                and hasattr(vehicle_state.radar, 'connected')
                and vehicle_state.radar.connected):
            if self._radar_cooldown > 0:
                return
            self._handle_radar_alert(vehicle_state.radar)
        # Otherwise: no radar, no fake alerts

    def _handle_radar_alert(self, radar_state):
        """Generate escalating first-person speech based on radar threat level."""
        if not radar_state or not radar_state.has_alerts:
            return

        alert = radar_state.priority_alert
        if not alert:
            return

        # Don't repeat for the same alert
        if alert.alert_id == self._last_radar_alert_id:
            return

        signal = max(alert.front_signal, alert.rear_signal)
        if signal < 1:
            return

        self._last_radar_alert_id = alert.alert_id
        # Cooldown: don't spam — wait 8 seconds between radar speeches
        self._radar_cooldown = 8

        band = alert.band.value
        direction = alert.direction.value

        if alert.band == RadarBand.LASER:
            line = f"LASER! {direction.upper()}! You're being painted right now."
            urgency = "critical"
        elif signal <= 2:
            line = f"Heads up — weak {band} detected, {direction}."
            urgency = "alert"
        elif signal <= 4:
            ghz = alert.frequency_mhz / 1000.0
            line = f"I'm picking up {band} at {ghz:.1f} GHz, {direction}. Signal is building."
            urgency = "alert"
        elif signal <= 6:
            ghz = alert.frequency_mhz / 1000.0
            line = f"Strong {band} {direction}, {ghz:.1f} GHz. Slow it down."
            urgency = "alert"
        else:
            ghz = alert.frequency_mhz / 1000.0
            line = f"Very strong {band} signal, {ghz:.1f} GHz! Brake check."
            urgency = "critical"

        self._queue_lines([line], urgency=urgency)
